### ISSUE TITLE
Feature requirement: Internal address restriction IP prefix function

### ISSUE THREAD

**Issue by InPRTx** [EHfive/einat-ebpf#21]
I did not find any function to limit the internal address range or network card for NAT operation.
When the internal network has public IP addresses and private addresses on the same network card, I hope to perform NAT operation only on private addresses.

我没有找到限制NAT操作的内部地址范围或网卡的功能。
在同一个网卡上，内部网络有公网IP地址和私网地址的时候，我希望仅有私网地址进行NAT操作。

**Target Machine (please complete the following information):**

-   Architecture:  x86-64
-   Linux distribution: Debian12
-   Kernel version: 6.11.6-x64v3-xanmod1
-   einat version: 0.1.2

**Comment by InPRTx** [comment]
![image](https://github.com/user-attachments/assets/02af68e2-4110-423a-ab9d-86a2da7d7363)
![image](https://github.com/user-attachments/assets/3106de3e-9bdc-47cd-b1c5-6d05476080e9)

Problems caused by too wide an internal NAT range
作用的内部NAT范围太宽泛造成的问题

**Comment by EHfive** [comment]
>  When the internal network has public IP addresses and private addresses on the same network card, I hope to perform NAT operation only on private addresses.

You mean you have public IP address on your internal interface rather than external interface? This is either invalid or you have a very special network routing setup. Please elaborate your network topology so we can do analysis of the case.

Also I am not going to parse your figures without any annotation. Please describe what's unexpected and what you are expecting.

Regarding your request of passing through NAT from specific source address, this is only possible if that address is or acted as external address attached on external interface, otherwise einat would not know to which internal source to DNAT.

```toml
[[interfaces]]
# ...

# prepend this externals config
[[interfaces.externals]]
# passing through SNAT for this address
address = "<your extra external address>"
no_snat = true
no_hairpin = true
```

**Comment by InPRTx** [comment]
@EHfive 
I have some public ipv4 addresses, and my machines below me use dhcp to assign private ipv4 addresses to them by default, but I can statically bind my public ipv4 addresses to my machines below me. There is a problem with this tool at the moment, it seems to perform all nat operations on the internal 0.0.0.0/0 addresses, and I wonder if your tool can be improved to add a function to bind only to a certain internal network card or certain internal network segments.

我有一些公网ipv4地址，我的下面机器默认dhcp分配私有ipv4给机器，但是我可以在我下面的机器静态绑定我的公网ipv4。目前这个工具有个问题，它似乎将内部0.0.0.0/0地址进行了全部nat操作，我想你的工具能不能进行改进，增加一个绑定只处理某个内部网卡或某一些内部网段的功能。

**Comment by EHfive** [comment]
Still don't clear what's you are expecting, please describe your network topology in concrete example, especially your routing setup as this is an uncommon use case.

> it seems to perform all nat operations on the internal 0.0.0.0/0 addresses

This is expected and the nature of Endpoint-Independent Mapping.

For example if your have an external address `233.252.0.200` and an internal source already occupies port `233.252.0.200:54321`, the traffic from `0.0.0.0:54321` would have to use another port to avoid conflict otherwise the 1-to-1 Endpoint-Independent Mapping guarantees would be broken.

However if you just want to expose some internal service port, you can exclude them from `tcp_ranges` or `udp_ranges`.

**Comment by InPRTx** [comment]
@EHfive 
Let me give you an example. Your current program looks like this:
iptables -t nat -A POSTROUTING -j MASQUERADE
But I hope your program can do this:
iptables -t nat -A POSTROUTING -s 10.100.0.0/24 -j MASQUERADE
Your program seems to perform NAT conversion on all source addresses from the internal network.
I need it to limit the source address range of the internal network to a certain interface or a certain segment.

我打个比方，你现在的程序像是这样
iptables -t nat -A POSTROUTING -j MASQUERADE
但我希望你的程序能这：
iptables -t nat -A POSTROUTING -s 10.100.0.0/24 -j MASQUERADE
你的程序，似乎对来自内部网络的全部原地址进行nat转换。
我需要它能将内部网络源地址范围限制为某个某个接口或某个段。

**Comment by InPRTx** [comment]
a1(ip:23.x.x.x/32,gw:10.100.22.1)
a2(ip:10.100.22.20/24,gw:10.100.22.1)
a1 and a2 are in the same network


b(ip:10.100.22.1/32,10.100.20.22/24,gw:10.100.20.1)
c(ip:10.100.20.1/24,103.x.x.x/24) run einat-ebpf


When machine c receives data from 10.100.0.0/16, it performs NAT conversion. 
When machine c receives data from 23.x.x.x/32, it does not perform NAT conversion and bypasses the operation.


当机器c收到来自10.100.0.0/16进行nat转换
当机器c收到来自23.x.x.x/32不进行nat转换，直接绕过操作

**Comment by EHfive** [comment]
> iptables -t nat -A POSTROUTING -s 10.100.0.0/24 -j MASQUERADE

In reply to this:



> For example if your have an external address 233.252.0.200 and an internal source already occupies port 233.252.0.200:54321, the traffic from 0.0.0.0:54321 would have to use another port* to avoid conflict otherwise the 1-to-1 Endpoint-Independent Mapping guarantees would be broken.

As I said above, what you expected is against the nature of Endpoint-Independent Mapping, it's not possible to bypass arbitrary internal source that unroutable from external network for a EIM + EIF NAT.

If you want to understand more about EIM, read my blog https://eh5.me/zh-cn/blog/nat-behavior-explained.

---

> When machine c receives data from 23.x.x.x/32, it does not perform NAT conversion and bypasses the operation.

So you have special routing rules setup and the `23.x.x.x/32` is acted as an external address attached on external interface of machine c? Then just apply the `no_snat` trick above.

> Regarding your request of passing through NAT from specific source address, this is only possible if that address is or acted as external address attached on external interface, otherwise einat would not know to which internal source to DNAT.

```toml
[[interfaces]]
# ...

# prepend this externals config
[[interfaces.externals]]
# passing through SNAT for this address
address = "<your extra external address>"
no_snat = true
no_hairpin = true
```

Seems you are not reading my comments carefully, it's sad..

Closing as answered.
